//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaNews.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoronaNews.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif vaka.
        /// </summary>
        public static string ActiveCases {
            get {
                return ResourceManager.GetString("ActiveCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar deneyin.
        /// </summary>
        public static string App_StopButton {
            get {
                return ResourceManager.GetString("App_StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama erişimi sırasında bir hata oluştu.
        ///Lütfen internet bağlantınızı kontrol edin ve bir süre sonra tekrar deneyin..
        /// </summary>
        public static string App_StopMessage {
            get {
                return ResourceManager.GetString("App_StopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaka.
        /// </summary>
        public static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir milyonda vaka.
        /// </summary>
        public static string casesPerOneMillion {
            get {
                return ResourceManager.GetString("casesPerOneMillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülkeler.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülke listesi.
        /// </summary>
        public static string CountryList {
            get {
                return ResourceManager.GetString("CountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritik.
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölüm.
        /// </summary>
        public static string Death {
            get {
                return ResourceManager.GetString("Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir milyonda ölüm.
        /// </summary>
        public static string deathsPerOneMillion {
            get {
                return ResourceManager.GetString("deathsPerOneMillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string Lang_en {
            get {
                return ResourceManager.GetString("Lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string Lang_tr {
            get {
                return ResourceManager.GetString("Lang_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana sayfaya geri dön.
        /// </summary>
        public static string Message_HomeButton {
            get {
                return ResourceManager.GetString("Message_HomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Message_TitleError {
            get {
                return ResourceManager.GetString("Message_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tebrikler.
        /// </summary>
        public static string Message_TitleInfo {
            get {
                return ResourceManager.GetString("Message_TitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string Message_TitleWarning {
            get {
                return ResourceManager.GetString("Message_TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İyileşenler.
        /// </summary>
        public static string Recovered {
            get {
                return ResourceManager.GetString("Recovered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir milyonda test.
        /// </summary>
        public static string testsPerOneMillion {
            get {
                return ResourceManager.GetString("testsPerOneMillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugünkü vakalar.
        /// </summary>
        public static string TodayCases {
            get {
                return ResourceManager.GetString("TodayCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugünkü ölümler.
        /// </summary>
        public static string TodayDeath {
            get {
                return ResourceManager.GetString("TodayDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dünya.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
